#ifndef PREDEFINED_SYMBOLS_HPP_INCLUDED
#define PREDEFINED_SYMBOLS_HPP_INCLUDED 0

extern const char* PredefinedSymbols[4];

enum {
    SYMBOL_GET_INTERFACE_ID,
    SYMBOL_GET_IMPLEMENTATION_ID,
    SYMBOL_GET_INTERFACE_NAME,
    SYMBOL_GET_IMPLEMENTATION_NAME
};

#endif // PREDEFINED_SYMBOLS_HPP_INCLUDED
